#!/bin/bash

echo "🚂 Railway Deployment Status Check"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📋 Instructions:"
echo ""
echo "1. Go to: https://railway.app/dashboard"
echo "2. Click on your Maxxit project"
echo "3. Click on your service"
echo "4. Click 'Deployments' tab"
echo "5. Click latest deployment"
echo "6. Click 'View Logs'"
echo ""
echo "Look for these messages:"
echo ""
echo "✅ GOOD SIGNS:"
echo "   • '✅ Tweet Ingestion started (PID: XXX)'"
echo "   • '✅ Signal Generator started (PID: XXX)'"
echo "   • '✅ Trade Executor started (PID: XXX)'"
echo "   • '✅ Position Monitor started (PID: XXX)'"
echo "   • '🎉 All workers started successfully!'"
echo ""
echo "❌ BAD SIGNS:"
echo "   • 'Error: ...' (any error messages)"
echo "   • 'ECONNREFUSED' (can't connect to database)"
echo "   • 'No authentication method available'"
echo "   • Workers not showing PIDs"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 Or check with Railway CLI:"
echo "   railway logs --follow"
echo ""


